security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
    role_hierarchy:
        # The role ROLE_ADMIN with the ROLE_ALLOWED_TO_SWITCH, which makes it possible to be authenticated
        # by pretending to be any member. Especially useful for debugging its code.
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            user_checker: App\Security\UserChecker
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginAuthenticator
            form_login:
                provider: app_user_provider
                login_path: /login
                check_path: /login

            logout:
                path: app_logout

            remember_me:
                secret: "%kernel.secret%"
                lifetime: 604800 # 1 week in seconds
                path: /

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
